//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamezServer.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platform
    {
        public long ID { get; set; }
        public string PlatformID { get; set; }
        public string PlatformName { get; set; }
        public string PlatformUniqueName { get; set; }
    }
}
